title: Delphic Node
brief-intro: Space Scientist
email: delphic.node@proton.me
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" 
url: "http://lethean-scribe.github.io" 
twitter_username: LScribe32851
github_username: lethean-scribe
facebook_username: lethean-scribe
email: delphic.node@proton.me
weibo_username: lethean-scribe
zhihu_username: lethean-scribe
linkedIn_username: lethean-scribe-3a6202387
dribbble_username: hypersocks
duoshuo_shortname: lethean-scribe
disqus_shortname: letheanscribe
reddit_username: Lethean-Scribe
tiktok_username: lethean.scribe
medium_username: delphic.node
x_username: LScribe32851

description_footer: Floating on the river of forgetfulness.

# Build settings
paginate: 5
paginate_path: "/page:num/"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-
  
header_pages:
  - about.md
  - newsletter.md
  - archive.md
