name: Publish to Social Media
on:
  push:
    branches: [ main ]
    paths: [ '_posts/**' ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install praw tweepy requests feedparser pillow google-api-python-client python-wordpress-xmlrpc Mastodon.py
    
    #- name: Publish to Reddit
    #  env:
    #    REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
    #    REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
    #    REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
    #    REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
    #  run: python .github/workflows/reddit-publisher.py
    
    # - name: Publish to Twitter
    #  env:
    #    TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
    #    TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
    #    TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
    #    TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    #  run: python .github/workflows/twitter-publisher.py
    
    - name: Publish to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: python .github/workflows/discord-publisher.py
    
    - name: Publish to WordPress
      env:
        WORDPRESS_SITE_ID: ${{ secrets.WORDPRESS_SITE_ID }}
        WORDPRESS_ACCESS_TOKEN: ${{ secrets.WORDPRESS_ACCESS_TOKEN }}
        WORDPRESS_URL: ${{ secrets.WORDPRESS_URL }}
        WORDPRESS_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
        WORDPRESS_APP_PASSWORD: ${{ secrets.WORDPRESS_APP_PASSWORD }}
      run: python .github/workflows/wordpress-publisher.py
    
    - name: Publish to Mastodon
      env:
        MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
        MASTODON_INSTANCE: ${{ secrets.MASTODON_INSTANCE }}
      run: python .github/workflows/mastodon-publisher.py
